### PR TITLE
Discord issue 85

### PR DESCRIPTION
**Pull request by iNikitaGricenko**
Issue #85 and #86 fix

### CODE REVIEW

**Comment by anna-geller** [comment]
with respect to #85 - the link still doesn't look good -- could you modify that so that it looks as here @iNikitaGricenko?

image

**Comment by anna-geller** [comment]
whatever payload I tried, the incoming webhook currently always returns either empty body or invalid json:

image

can you try using a similar payload as in this curl request? https://github.com/kestra-io/plugin-notifications/issues/85#issue-1935519251

**Comment by anna-geller** [comment]
only port is wrong, after that we can merge 🚀

**Comment by tchiotludo** [comment]
@iNikitaGricenko you can handle please?

**Comment by iNikitaGricenko** [comment]
> @iNikitaGricenko you can handle please?

Port or conflict?
About port, I'm not specify it, but getting current launcher (who is running) same as it is in slack plugin. But can try to find other way to do it

**Pull request closed without merging**
